version: '3.7'

services:
  doom1:
    image: rcdailey/zandronum-server:tspg-latest
    build:
      context: source
      args:
      - REPO_URL=https://bitbucket.org/thesentinelsplayground/zatspg-release
      - REPO_TAG=TSPGv12
    restart: always
    network_mode: host
    volumes:
    - ./data:/data:ro
    - ./configs:/configs:ro
    command: >
      -port 10666
      -iwad /data/pretend_doom.wad
      -file /data/pretend_brutal_doom.pk3
      +exec /configs/global.cfg
      +exec /configs/coop.cfg
      +exec /configs/doom1_maps.cfg
      +sv_hostname "The Doom 1 Coop Server"

  doom2:
    image: rcdailey/zandronum-server:tspg-latest
    build:
      context: source
      args:
      - REPO_URL=https://bitbucket.org/thesentinelsplayground/zatspg-release
      - REPO_TAG=TSPGv12
    restart: always
    network_mode: host
    volumes:
    - ./data:/data:ro
    - ./configs:/configs:ro
    command: >
      -port 10667
      -iwad /data/pretend_doom2.wad
      -file /data/pretend_brutal_doom.pk3
      +exec /configs/global.cfg
      +exec /configs/coop.cfg
      +exec /configs/doom2_maps.cfg
      +sv_hostname "The Doom 2 Coop Server"

  lexicon:
    image: rcdailey/zandronum-server:tspg-latest
    restart: always
    network_mode: host
    volumes:
    - ./data:/data:ro
    - ./configs:/configs:ro
    command: >
      -port 10668
      -iwad /data/pretend_doom2.wad
      -file /data/pretend_sentinels_lexicon.pk3
      +sv_hostname "The Sentinel Lexicon Server"
      +exec /configs/global.cfg
      +exec /configs/coop.cfg
      +map VR
      +lexicon_timer_start 60
